language: python

python:
  - "3.7"

install:
  - pip install tox-travis
  - pip install nodeenv
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then pip install coveralls -e .; fi

script:
  - tox
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then coverage run -m pytest tests; fi

after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then coveralls; fi

notifications:
  email: false